name: Submodules Update
on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive
      - name: Setup Git Profile
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Update Submodules
        run: git submodule update --init --remote
      - name: Commit
        run: "git diff --quiet && git diff --staged --quiet || git commit -am 'auto: update submodules'"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
